### ISSUE TITLE
Can't seem to compile with brew installed neovim

### ISSUE THREAD

**Issue by bulkan** [rogual/neovim-osx-gui#1]
I have installed neovim via https://github.com/neovim/neovim/wiki/Installing#os-x--homebrew and msgpack-c via `brew install msgpack`

[The output from make](https://gist.github.com/bulkan/2f33de879295b1d6ee4e)

**Comment by rogual** [comment]
I believe the EXT type is a fairly recent addition to msgpack and it looks like Homebrew's version doesn't have it. I'd recommend compiling msgpack-c yourself from their Git repo to get an up-to-date version.

**Comment by bulkan** [comment]
awesome that worked !

**Comment by Pyrohh** [comment]
EXT was added a while ago, but a new release of `msgpack-c` was only recently made. I'll send a PR to homebrew now.

**Comment by Pyrohh** [comment]
@rogual @bulkan msgpack in homebrew was just updated to the latest release, could you try it out and update the instructions if it works?

**Comment by rogual** [comment]
Done.

**Comment by Pyrohh** [comment]
thanks

**Comment by james2doyle** [comment]
I had to [install msgpack-c from source](https://github.com/msgpack/msgpack-c#install-from-git-repository) before make would complete successfully.

**Comment by rogual** [comment]
Did make give you an error message?

**Comment by james2doyle** [comment]
Yeah it was the same error as the linked gist before the source build of
msgpack-c

**Comment by rogual** [comment]
Sounds like it's still using the old version of msgpack. Is your Homebrew up to date?

```
brew uninstall msgpack
brew update
brew install msgpack
```

**Comment by jdavis** [comment]
@james2doyle @rogual I just went to install it and had the same issue.

My problem was that I had installed msgpack without running `brew update` so I was installing the outdated version. What @rogual posted fixed it:

```
brew uninstall msgpack
brew update
brew install msgpack
```

**Comment by james2doyle** [comment]
You know what, I think you are right. I ran `brew update` and `msgpack` showed up in the update results. Maybe add a line in the README to make sure people do that before?
