### ISSUE TITLE
Fullscreen file list is in wrong position

### ISSUE THREAD

**Issue by bulkan** [rogual/neovim-osx-gui#2]
* Go full screen (or make window a little higher/wider) 
* Then hit `:e` tab

Notice how file listing tab completion suggestion is not correctly aligned

https://www.youtube.com/watch?v=BxlGYqKC9FE&feature=youtu.be

Interestingly CtrlP and command suggesting works.

**Comment by rogual** [comment]
Thanks for this! This is now fixed as of https://github.com/rogual/neovim-osx-gui/commit/3555526d81cd13201a0dd1e9dd255953b01c9471.
