### ISSUE TITLE
Slow redrawing

### ISSUE THREAD

**Issue by rogual** [rogual/neovim-osx-gui#5]
I had a look at why NeoVim.app doesn't feel as responsive as MacVim or terminal nvim. It turns out the bottleneck is the redraw code.

Here's how redrawing works now:

The view has a member `NSImage *mCanvas`. When Vim tells us to draw some stuff, we:
1. `[mCanvas lockFocus]`
2. Draw things. If this includes scrolling, we also unlock/lock the canvas for each scroll call, otherwise the canvas doesn't update properly for some reason.
3. `[mCanvas unlockFocus]`
4. `[view display]`

When we call `display`, Cocoa calls our view's `drawRect` method, which copies the canvas to the screen using `[mCanvas drawInRect:...]`

### Why is this slow?

`lockFocus (NSImage)` is *very* slow — it appears to copy and convert the entire image — so we can't keep calling it every redraw, let alone multiple times per redraw. 

#### NSGraphicsContext

`lockFocus` is really just a convenience method that sets the current graphics context to one that will draw to the image. If we managed our own graphics context we might be able to do this more efficiently. I had a go at keeping our own NSImageRepresentation and NSGraphicsContext inside the view, but I couldn't get Cocoa to draw anything that way.

The NSGraphicsContext docs are well below Apple's normal (dire) standards, though, so it's possible I was doing totally the wrong thing.

If anyone picks this up and ends up reading [these docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSGraphicsContext_Class/index.html), save yourself some hair-pulling and ignore the paragraph about graphics contexts being saved on a stack. It's utter horseshit: the only way to set the current graphics context is with `setCurrentContext`. The save/restore methods seem to only affect state *within* the current context.

#### CoreImage

Maybe look into this. If we go this way we can use filters to draw the cursor properly too

#### Do all rendering in drawRect

We give up trying to render to a buffer. Instead, when redraw calls come in from Vim, we add them to a queue, call setNeedsDisplay, and only decode the calls inside drawRect. This seems like it might better fit the “cocoa way” of doing things, but it does mean we'd need to copy the entire msgpack object when we receive it, and right now I don't know how to do that in msgpack (object data is stored in a separate buffer whose lifetime is tied to that of the unpacker object).

### Other thoughts

This should be simple. All we want to do is render to an offscreen buffer then blit it to the screen when it's time to redraw the view, without doing any copying, resizing, format conversion, etc.

Other people's notes on offscreen drawing:
* http://orangejuiceliberationfront.com/drawing-off-screen-in-cocoa/

**Comment by bugeats** [comment]
I know very little about cocoa, but which approach would open the possibility of doing things like:

- animating highlighted search terms
- zoom out tiling of all open tab pages / minimap like stuff
- rendering a dynamic cursor
- smooth scrolling

**Comment by bugeats** [comment]
It occurs to me that you can leverage a fundamental design constraint of Neovim: it's all just a relatively small amount of rows and columns. Maybe you can directly address / redraw individual cells in the matrix. Opens up diff optimization algorithms and such.

**Comment by rogual** [comment]
I'm going to close this because I'm happy with the drawing speed after https://github.com/rogual/neovim-osx-gui/commit/fa72102fa8771ee773b043c0c5aa33b1973961a3.

But, we should absolutely consider those features, @bugeats. Feel free to open separate issues for them.

**Comment by snatchev** [comment]
@rogual just out of curiosity, how are you measuring drawing speed? Are you eyeballing it?

**Comment by rogual** [comment]
Yeah, I'm using the super scientific method of what “feels fast”.

**Comment by snatchev** [comment]
Good enough for now! Sadly, I don't know that much about graphics programming to contribute.

**Comment by CodeFalling** [comment]
I use the same way with  fa72102  in another project.Kill the slow `-lockFocus`,but got a slow `-drawRect`.Not "feels fast" at all.
